import { QuestionDefinition } from "@/lib/diagnostics/types";

const riskOptions = [
  { value: 0 as const, label: "Not true", description: "This is not a meaningful issue in the workflow." },
  { value: 1 as const, label: "Occasional", description: "This shows up sometimes, but usually remains manageable." },
  { value: 2 as const, label: "Frequent", description: "This is a recurring blocker and requires manual workarounds." },
  { value: 3 as const, label: "Systemic", description: "This is structural and routinely undermines trust or speed." },
];

const maturityOptions = [
  { value: 0 as const, label: "Not in place", description: "This capability is absent or ad hoc." },
  { value: 1 as const, label: "Partly in place", description: "Some elements exist, but they are inconsistent." },
  { value: 2 as const, label: "Mostly in place", description: "The capability exists for this workflow with some gaps." },
  { value: 3 as const, label: "Systematic", description: "The capability is designed, owned, and repeatable." },
];

export const questionBank: QuestionDefinition[] = [
  {
    id: "manual_dependency",
    shortLabel: "Manual assembly",
    prompt: "How dependent is this workflow on spreadsheets, email requests, or one-off manual assembly before analysis can begin?",
    helpText: "High scores indicate DRL 1-2 style operating patterns and weak repeatability.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      resource_limitations: 0.8,
      volume_processing: 0.5,
      system_integration: 0.8,
    },
    signalWeights: {
      manual_collection_risk: 1,
      digital_foundation: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "source_conflict",
    shortLabel: "Source conflict",
    prompt: "How often do the same workforce metrics or entities disagree across systems such as HRIS, ATS, payroll, surveys, or performance tools?",
    helpText: "This is the core signal for root condition 1 and often exposes weak information architecture.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      multiple_data_sources: 1,
      system_integration: 0.7,
      diverse_coding_systems: 0.3,
    },
    signalWeights: {
      byproduct_dependence: 0.8,
    },
    options: riskOptions,
  },
  {
    id: "subjective_capture",
    shortLabel: "Subjective capture",
    prompt: "How much of the decision-quality data in this workflow still depends on manager judgement, self-report, or free-text interpretation?",
    helpText: "High scores indicate a structural gap between human judgement and machine-readable evidence.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      subjective_judgement: 1,
      complex_representation: 0.7,
      input_standards: 0.4,
    },
    signalWeights: {
      structured_ai_readiness: 0.5,
      byproduct_dependence: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "access_friction",
    shortLabel: "Access friction",
    prompt: "How often do access restrictions, approval chains, or missing capacity delay the data needed for this workflow?",
    helpText: "This distinguishes technical absence from operational inaccessibility.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      resource_limitations: 0.8,
      security_access_balance: 1,
      system_integration: 0.3,
    },
    signalWeights: {
      dpm_ownership: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "taxonomy_mismatch",
    shortLabel: "Taxonomy mismatch",
    prompt: "How often do role, level, location, function, or skill taxonomies need recoding before this workflow becomes usable?",
    helpText: "High scores indicate joinability and comparability issues, even when source systems are available.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      diverse_coding_systems: 1,
      multiple_data_sources: 0.5,
      system_integration: 0.5,
    },
    signalWeights: {
      byproduct_dependence: 0.5,
    },
    options: riskOptions,
  },
  {
    id: "representation_complexity",
    shortLabel: "Representation complexity",
    prompt: "How much of the important signal sits in free text, vendor-specific formats, screenshots, or narrative notes instead of structured fields?",
    helpText: "High scores raise AI risk because the signal needs translation before reuse.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      complex_representation: 1,
      subjective_judgement: 0.4,
      input_standards: 0.3,
    },
    signalWeights: {
      structured_ai_readiness: 0.7,
      advanced_ai_integration: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "volume_drag",
    shortLabel: "Volume drag",
    prompt: "How often does data volume or repeated extraction create processing drag without improving the quality of the final decision signal?",
    helpText: "This separates signal quality from raw collection scale.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      volume_processing: 1,
      resource_limitations: 0.4,
      complex_representation: 0.3,
    },
    signalWeights: {
      byproduct_dependence: 0.5,
      advanced_ai_integration: 0.3,
    },
    options: riskOptions,
  },
  {
    id: "input_variability",
    shortLabel: "Input variability",
    prompt: "How often do users bypass field rules, enter inconsistent values, or use free-form workarounds in this workflow?",
    helpText: "This is one of the strongest predictors of weak downstream trust and rework.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      input_standards: 1,
      subjective_judgement: 0.5,
      complex_representation: 0.3,
    },
    signalWeights: {
      tdqm_discipline: 0.4,
      structured_ai_readiness: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "requirements_drift",
    shortLabel: "Requirements drift",
    prompt: "How often are teams forced to reuse legacy fields or old business rules for a decision need they were not designed to support?",
    helpText: "High scores suggest the workflow has outgrown its original collection design.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      evolving_requirements: 1,
      input_standards: 0.3,
      system_integration: 0.3,
    },
    signalWeights: {
      data_product_discipline: 0.4,
      tdqm_discipline: 0.4,
    },
    options: riskOptions,
  },
  {
    id: "integration_gaps",
    shortLabel: "Integration gaps",
    prompt: "How much does this workflow rely on brittle joins, manual handoffs, or undocumented integration logic?",
    helpText: "A high score indicates weak architecture, weak ownership, or both.",
    direction: "risk",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      system_integration: 1,
      multiple_data_sources: 0.6,
      resource_limitations: 0.4,
    },
    signalWeights: {
      digital_foundation: 0.4,
      byproduct_dependence: 0.7,
    },
    options: riskOptions,
  },
  {
    id: "digital_foundation",
    shortLabel: "Digital foundation",
    prompt: "To what extent does this workflow already run on stable digital systems rather than manual or one-off collection methods?",
    helpText: "This distinguishes basic digital maturity from strategic data product maturity.",
    direction: "maturity",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      resource_limitations: 0.4,
      system_integration: 0.2,
    },
    signalWeights: {
      digital_foundation: 1,
      manual_collection_risk: 0.5,
    },
    options: maturityOptions,
  },
  {
    id: "data_product_design",
    shortLabel: "Data product design",
    prompt: "To what extent is the workflow intentionally designed as an information product with defined consumers, definitions, and reuse rules?",
    helpText: "This is the key threshold question separating DRL 5-6 from DRL 7.",
    direction: "maturity",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      multiple_data_sources: 0.4,
      evolving_requirements: 0.5,
      system_integration: 0.6,
      input_standards: 0.4,
    },
    signalWeights: {
      data_product_discipline: 1,
      byproduct_dependence: 0.8,
    },
    options: maturityOptions,
  },
  {
    id: "named_owner",
    shortLabel: "Named owner",
    prompt: "Is there a named cross-functional owner who can coordinate data producers, technical teams, and downstream consumers for this workflow?",
    helpText: "This approximates the DPM-style role described in the handbook.",
    direction: "maturity",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      resource_limitations: 0.5,
      security_access_balance: 0.3,
      system_integration: 0.7,
    },
    signalWeights: {
      dpm_ownership: 1,
      data_product_discipline: 0.3,
    },
    options: maturityOptions,
  },
  {
    id: "quality_management",
    shortLabel: "Quality management",
    prompt: "How systematic are the quality rules, monitoring checks, and remediation loops for this workflow?",
    helpText: "This captures the TDQM-style discipline required for DRL 7.",
    direction: "maturity",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      input_standards: 0.6,
      evolving_requirements: 0.5,
      resource_limitations: 0.3,
    },
    signalWeights: {
      tdqm_discipline: 1,
      structured_ai_readiness: 0.3,
    },
    options: maturityOptions,
  },
  {
    id: "ai_ready_structure",
    shortLabel: "AI-ready structure",
    prompt: "To what extent is the data in this workflow already structured for predictive or generative AI use without major recoding or caveat writing?",
    helpText: "This is the clearest direct indicator of whether AI can consume the workflow safely.",
    direction: "maturity",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {
      complex_representation: 0.6,
      input_standards: 0.5,
      multiple_data_sources: 0.3,
    },
    signalWeights: {
      structured_ai_readiness: 1,
      advanced_ai_integration: 0.3,
    },
    options: maturityOptions,
  },
  {
    id: "advanced_ai",
    shortLabel: "Advanced AI usage",
    prompt: "How directly does this workflow already support predictive, prescriptive, or other advanced AI-driven decisions?",
    helpText: "This question should remain conservative. Low scores are normal.",
    direction: "maturity",
    productTypes: ["dmm", "drl"],
    scopeTypes: ["use_case", "organization"],
    rootWeights: {},
    signalWeights: {
      advanced_ai_integration: 1,
    },
    options: maturityOptions,
  },
];
